# Generated by Django 2.2.24 on 2021-07-28 22:10

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepoPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_repo_stats_githubrepoplugin', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(help_text='Repo name as user/repo', max_length=255)),
                ('template', models.CharField(choices=[('default', 'Default')], default='default', max_length=255, verbose_name='Template')),
                ('data', django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='Data from github')),
            ],
            options={
                'verbose_name': 'github repo',
                'verbose_name_plural': 'github repos',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
